import nodemailer from 'nodemailer';
import config from './config.js';
import { logDigest } from './db.js';

const PRIORITY_EMOJI = {
  High: '🔴',
  Medium: '🟡',
  Low: '🟢',
};

/**
 * Sort analyzed threads by priority
 */
function sortByPriority(threads) {
  const order = { High: 0, Medium: 1, Low: 2 };
  return [...threads]
    .filter(t => t.priority !== 'Ignore')
    .sort((a, b) => (order[a.priority] || 2) - (order[b.priority] || 2));
}

// ─── SLACK ───────────────────────────────────────────────────────

function buildSlackBlocks(threads) {
  const blocks = [
    {
      type: 'header',
      text: { type: 'plain_text', text: `📧 Gmail Digest — ${new Date().toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' })}`, emoji: true },
    },
    { type: 'divider' },
  ];

  for (const t of threads) {
    const emoji = PRIORITY_EMOJI[t.priority] || '⚪';
    blocks.push(
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `${emoji} *${t.priority}* — *${t.subjectSummary || t.subject}*\n`
            + `_From: ${t.lastSender} (${t.senderType || 'Unknown'} - ${t.hoursSinceLastMessage}h ago)_\n\n`
            + (t.deadline ? `*⏱ Deadline:* ${t.deadline} (${t.deadlineContext})\n` : '')
            + (t.opportunityFlag ? `*📈 Opportunity:* ${t.opportunityType}\n` : '')
            + (t.financialFlag ? `*💰 Financial:* ${t.financialDetail}\n` : '')
            + (t.delegateTo && t.delegateTo !== 'Handle Yourself' ? `*👉 Delegate to:* ${t.delegateTo}\n` : '')
            + `*Why it matters:* ${t.whyItMatters}\n`
            + `*Risk:* ${t.riskOfNotReplying}\n`
            + `*Action:* ${t.recommendedAction}`,
        },
      }
    );

    if (t.draftReply) {
      blocks.push({
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: `💬 *Draft reply:*\n>${t.draftReply.split('\n').join('\n>')}`,
          },
        ],
      });
    }

    blocks.push({ type: 'divider' });
  }

  blocks.push({
    type: 'context',
    elements: [
      { type: 'mrkdwn', text: `_${threads.length} items · Generated at ${new Date().toLocaleTimeString('en-GB')}_` },
    ],
  });

  return blocks;
}

async function sendToSlack(threads) {
  const webhookUrl = process.env.SLACK_WEBHOOK_URL;
  if (!webhookUrl) {
    console.log('⚠️  No SLACK_WEBHOOK_URL set, skipping Slack delivery.');
    return false;
  }

  const blocks = buildSlackBlocks(threads);

  try {
    const res = await fetch(webhookUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ blocks }),
    });

    if (!res.ok) {
      console.error('❌ Slack delivery failed:', res.status, await res.text());
      return false;
    }

    console.log('✅ Digest sent to Slack');
    return true;
  } catch (err) {
    console.error('❌ Slack delivery error:', err.message);
    return false;
  }
}

// ─── EMAIL ───────────────────────────────────────────────────────

function buildEmailHtml(threads) {
  const date = new Date().toLocaleDateString('en-GB', {
    weekday: 'long', day: 'numeric', month: 'long', year: 'numeric',
  });

  const threadHtml = threads.map((t) => {
    const emoji = PRIORITY_EMOJI[t.priority] || '⚪';
    const draftSection = t.draftReply
      ? `<div style="background:#f0f4f8;padding:12px;border-radius:6px;margin-top:8px;border-left:3px solid #4a90d9;">
           <strong>💬 Draft reply:</strong><br/>
           <span style="white-space:pre-wrap;">${escapeHtml(t.draftReply)}</span>
         </div>`
      : '';

    return `
      <div style="border:1px solid #e2e8f0;border-radius:8px;padding:16px;margin-bottom:16px;">
        <div style="font-size:16px;font-weight:bold;margin-bottom:8px;">
          ${emoji} ${t.priority} — ${escapeHtml(t.subjectSummary || t.subject)}
        </div>
        <div style="color:#64748b;font-size:13px;margin-bottom:12px;">
          From: ${escapeHtml(t.lastSender)} (${escapeHtml(t.senderType || 'Unknown')}) · ${t.hoursSinceLastMessage}h ago
        </div>
        <div style="margin-bottom:6px;"><strong>Why it matters:</strong> ${escapeHtml(t.whyItMatters)}</div>
        <div style="margin-bottom:6px;"><strong>Risk:</strong> ${escapeHtml(t.riskOfNotReplying)}</div>
        <div style="margin-bottom:6px;"><strong>Action:</strong> ${escapeHtml(t.recommendedAction)}</div>
        ${draftSection}
      </div>`;
  }).join('');

  return `
    <div style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:640px;margin:0 auto;padding:20px;">
      <h2 style="color:#1e293b;">📧 Gmail Digest</h2>
      <p style="color:#64748b;">${date} · ${threads.length} items</p>
      ${threadHtml}
      <p style="color:#94a3b8;font-size:12px;text-align:center;margin-top:24px;">
        Generated by Gmail AI Assistant
      </p>
    </div>`;
}

function escapeHtml(text) {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

async function sendEmail(threads) {
  const { SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, DIGEST_TO_EMAIL } = process.env;
  if (!SMTP_HOST || !SMTP_USER || !DIGEST_TO_EMAIL) {
    console.log('⚠️  Email not configured, skipping email delivery.');
    return false;
  }

  const transporter = nodemailer.createTransport({
    host: SMTP_HOST,
    port: parseInt(SMTP_PORT) || 587,
    secure: false,
    auth: { user: SMTP_USER, pass: SMTP_PASS },
  });

  try {
    await transporter.sendMail({
      from: SMTP_USER,
      to: DIGEST_TO_EMAIL,
      subject: `📧 Gmail Digest — ${new Date().toLocaleDateString('en-GB', { weekday: 'short', day: 'numeric', month: 'short' })}`,
      html: buildEmailHtml(threads),
    });
    console.log('✅ Digest sent via email');
    return true;
  } catch (err) {
    console.error('❌ Email delivery failed:', err.message);
    return false;
  }
}

// ─── MAIN DELIVERY ──────────────────────────────────────────────

/**
 * Build and deliver the digest through configured channels
 */
export async function deliverDigest(analyzedThreads) {
  const maxItems = config.digest.maxItems || 7;
  const sorted = sortByPriority(analyzedThreads).slice(0, maxItems);
  const methods = config.digest.delivery || ['slack'];

  if (sorted.length === 0) {
    console.log('📭 No items to digest — inbox looks clean!');
    return;
  }

  console.log(`\n📋 Digest: ${sorted.length} item(s) to deliver via ${methods.join(', ')}\n`);

  // Print to console regardless
  for (const t of sorted) {
    const emoji = PRIORITY_EMOJI[t.priority] || '⚪';
    console.log(`${emoji} [${t.priority}] ${t.subjectSummary || t.subject}`);
    console.log(`   From: ${t.lastSender} (${t.senderType || 'Unknown'} - ${t.hoursSinceLastMessage}h ago)`);
    if (t.deadline) console.log(`   ⏱  Deadline: ${t.deadline} (${t.deadlineContext})`);
    if (t.opportunityFlag && t.opportunityType) console.log(`   📈 Opportunity: ${t.opportunityType}`);
    if (t.financialFlag && t.financialDetail) console.log(`   💰 Financial: ${t.financialDetail}`);
    if (t.legalFlag && t.legalContext) console.log(`   ⚖️  Legal: ${t.legalContext}`);
    if (t.delegateTo && t.delegateTo !== 'Handle Yourself' && t.delegateTo !== 'null') {
      console.log(`   👉 Delegate: ${t.delegateTo}`);
    }
    console.log(`   Why: ${t.whyItMatters}`);
    console.log(`   Risk: ${t.riskOfNotReplying}`);
    console.log(`   Action: ${t.recommendedAction}`);
    if (t.replyNeeded && t.draftReply) {
      console.log(`   Draft: ${t.draftReply.substring(0, 120)}...`);
    } else if (t.draftReply && t.replyNeeded !== false) {
      console.log(`   Draft: ${t.draftReply.substring(0, 120)}...`);
    }
    console.log('');
  }

  // Deliver via configured methods
  for (const method of methods) {
    let success = false;
    if (method === 'slack') {
      success = await sendToSlack(sorted);
    } else if (method === 'email') {
      success = await sendEmail(sorted);
    }
    logDigest(sorted.length, method, success);
  }
}
